-- ================================================================
-- TrainFlow - migracao segura para exercicios
-- ----------------------------------------------------------------
-- Uso:
-- 1) rode este arquivo em um banco ja existente
-- 2) ele adiciona colunas novas sem quebrar dados
-- 3) ele inclui exercicios faltantes no seed
-- ================================================================

alter table public.exercicios add column if not exists video_url text;
alter table public.exercicios add column if not exists observacao_cientifica text;
alter table public.treino_exercicios add column if not exists dia_semana text;
alter table public.treino_exercicios add column if not exists bloco_nome text;
alter table public.historico_treino add column if not exists dia_semana text;
alter table public.historico_treino add column if not exists bloco_nome text;

with seed_exercicios (
  nome,
  grupo_muscular,
  tipo,
  execucao,
  equipamento,
  observacao_cientifica,
  video_url
) as (
  values
    ('Hip Thrust', 'Glúteos', 'livre', 'Apoie bem as escápulas no banco, mantenha o queixo recolhido e finalize com retroversão pélvica leve, sem hiperestender a lombar.', 'Banco, barra, anilhas', 'Excelente para alta tensão em glúteos com boa estabilidade. Pausas no pico costumam aumentar percepção de contração sem exigir tantas cargas extras.', 'https://www.youtube.com/results?search_query=hip+thrust+execucao+certa'),
    ('Hip Thrust com Pausa', 'Glúteos', 'livre', 'Segure 1–2 segundos no topo, empurre pelos calcanhares e desça sem perder controle da pelve.', 'Banco, barra, anilhas', 'A pausa no topo eleva tempo sob tensão na posição de maior encurtamento e reduz o impulso mecânico entre repetições.', 'https://www.youtube.com/results?search_query=hip+thrust+com+pausa+execucao'),
    ('Hip Thrust Moderado', 'Glúteos', 'livre', 'Use carga moderada, reps controladas e foque em ritmo estável do início ao fim da série.', 'Banco, barra, anilhas', 'Versões moderadas ajudam a acumular volume útil com menor custo articular, especialmente em semanas mais carregadas.', 'https://www.youtube.com/results?search_query=hip+thrust+execucao+certa'),
    ('Stiff / Terra Romeno', 'Pernas', 'livre', 'Desça empurrando o quadril para trás, mantenha a barra próxima ao corpo e preserve a coluna neutra durante toda a amplitude.', 'Barra, anilhas', 'Padrão dominante de quadril muito eficiente para posteriores quando a descida é controlada e a amplitude respeita mobilidade individual.', 'https://www.youtube.com/results?search_query=stiff+terra+romeno+execucao'),
    ('Levantamento Terra Convencional', 'Pernas', 'livre', 'Crie pressão no tronco, aproxime a barra da canela e inicie o movimento empurrando o chão, sem perder rigidez axial.', 'Barra, anilhas', 'Exercício de alta demanda sistêmica. Costuma exigir mais descanso e melhor gestão de fadiga dentro da semana.', 'https://www.youtube.com/results?search_query=levantamento+terra+convencional+execucao'),
    ('Mesa Flexora Sentada', 'Pernas', 'maquina', 'Ajuste o encosto, mantenha quadril estável e flexione os joelhos sem tirar o quadril do assento.', 'Mesa flexora sentada', 'A posição sentada tende a colocar posteriores em maior alongamento no quadril, o que pode favorecer estímulo mecânico.', 'https://www.youtube.com/results?search_query=mesa+flexora+sentada+execucao'),
    ('Mesa Flexora', 'Pernas', 'maquina', 'Flexione os joelhos com ritmo controlado e evite tirar o quadril do apoio no final das reps.', 'Mesa flexora', 'Boa opção para complementar padrões de quadril com estímulo mais localizado em flexão de joelhos.', 'https://www.youtube.com/results?search_query=mesa+flexora+execucao'),
    ('Mesa Flexora Leve', 'Pernas', 'maquina', 'Use carga confortável, tempo controlado e amplitude limpa para acumular volume com baixa fadiga.', 'Mesa flexora', 'Versões leves funcionam bem para recuperação ativa, acabamento ou semanas com ênfase maior em compostos.', 'https://www.youtube.com/results?search_query=mesa+flexora+execucao'),
    ('Agachamento Búlgaro', 'Pernas', 'livre', 'Desça em linha reta, mantenha o tronco firme e distribua a carga principalmente na perna da frente.', 'Banco, halteres', 'Unilateral valioso para estabilidade, glúteos e quadríceps, além de ajudar a equalizar assimetrias.', 'https://www.youtube.com/results?search_query=agachamento+bulgaro+execucao'),
    ('Avanço com Halteres', 'Pernas', 'livre', 'Dê passos controlados, mantenha a passada estável e evite usar o impulso para sair do fundo.', 'Halteres', 'Ótimo para combinar estímulo de quadríceps e glúteos com demanda moderada de estabilidade.', 'https://www.youtube.com/results?search_query=avanco+com+halteres+execucao'),
    ('Agachamento Livre', 'Pernas', 'livre', 'Inspire antes de descer, mantenha o tronco organizado e procure amplitude consistente sem perder alinhamento dos joelhos.', 'Barra, rack', 'Base clássica para quadríceps e glúteos. Responde bem a progressão gradual, frequência regular e controle de fadiga.', 'https://www.youtube.com/results?search_query=agachamento+livre+execucao'),
    ('Hack Squat', 'Pernas', 'maquina', 'Apoie bem o quadril, desça com controle e pressione a plataforma sem travar os joelhos no topo.', 'Máquina hack', 'Permite alta estabilidade e proximidade da falha com menor exigência técnica que o agachamento livre.', 'https://www.youtube.com/results?search_query=hack+squat+execucao'),
    ('Leg Press 45°', 'Pernas', 'maquina', 'Desça até a amplitude que preserve quadril apoiado, controle a excêntrica e empurre com o pé inteiro na plataforma.', 'Leg press 45°', 'Muito útil para acumular volume pesado em quadríceps com estabilidade alta e boa margem de segurança.', 'https://www.youtube.com/results?search_query=leg+press+45+execucao'),
    ('Cadeira Extensora', 'Pernas', 'maquina', 'Ajuste o eixo do joelho, estenda sem impulso e controle a volta até quase a flexão total.', 'Cadeira extensora', 'Boa para pré-ativação e para elevar volume local de quadríceps com baixa complexidade técnica.', 'https://www.youtube.com/results?search_query=cadeira+extensora+execucao'),
    ('Extensora (Ativação)', 'Pernas', 'maquina', 'Use carga leve a moderada, foco em conexão com quadríceps e reps fluidas antes dos compostos.', 'Cadeira extensora', 'Pré-ativação pode melhorar percepção muscular e aquecimento específico antes de agachar ou pressionar.', 'https://www.youtube.com/results?search_query=cadeira+extensora+execucao'),
    ('Adutora na Máquina', 'Pernas', 'maquina', 'Mantenha o quadril estável no assento e feche as pernas sem perder o controle da fase de retorno.', 'Máquina adutora', 'Adutores também contribuem para estabilidade pélvica e desempenho em padrões de agachamento.', 'https://www.youtube.com/results?search_query=adutora+na+maquina+execucao'),
    ('Adutora Leve', 'Pernas', 'maquina', 'Use ritmo constante e foco em amplitude confortável para adicionar volume com baixo custo de fadiga.', 'Máquina adutora', 'Versões leves servem bem como complemento em semanas com alto volume de pernas.', 'https://www.youtube.com/results?search_query=adutora+na+maquina+execucao'),
    ('Abdutora na Máquina', 'Glúteos', 'maquina', 'Mantenha a pelve apoiada e abra as pernas sem compensar com balanço do tronco.', 'Máquina abdutora', 'Boa para glúteo médio e estabilidade de quadril, especialmente em blocos com bastante trabalho unilateral.', 'https://www.youtube.com/results?search_query=abdutora+na+maquina+execucao'),
    ('Abdução na Polia', 'Glúteos', 'maquina', 'Afaste a perna com controle, segurando o tronco firme e sem inclinar excessivamente o corpo.', 'Polia baixa, caneleira', 'Ótima para glúteo médio com curva de resistência contínua e fácil ajuste fino de carga.', 'https://www.youtube.com/results?search_query=abducao+na+polia+execucao'),
    ('Coice na Polia', 'Glúteos', 'maquina', 'Estenda o quadril com o pé ativo e sem jogar a lombar para trás durante o final do movimento.', 'Polia baixa, caneleira', 'Funciona bem como acessório para glúteos em faixas moderadas a altas de repetições.', 'https://www.youtube.com/results?search_query=coice+na+polia+execucao'),
    ('Panturrilha em Pé', 'Pernas', 'maquina', 'Faça pausa curta no alongamento e suba o máximo possível sem quicar na base.', 'Máquina de panturrilha em pé', 'Tende a enfatizar gastrocnêmio e responde bem a amplitude completa e pausas breves no alongamento.', 'https://www.youtube.com/results?search_query=panturrilha+em+pe+execucao'),
    ('Panturrilha Sentada', 'Pernas', 'maquina', 'Desça com controle total e suba até a contração máxima, mantendo o joelho estável.', 'Máquina de panturrilha sentada', 'Com o joelho flexionado, a versão sentada aumenta a participação do sóleo.', 'https://www.youtube.com/results?search_query=panturrilha+sentada+execucao'),
    ('Panturrilha Sentada (Sóleo)', 'Pernas', 'maquina', 'Mantenha o tornozelo livre, pause no alongamento e controle o pico de contração no topo.', 'Máquina de panturrilha sentada', 'Excelente para enfatizar sóleo, importante para volume de panturrilhas e tolerância a trabalho repetido.', 'https://www.youtube.com/results?search_query=panturrilha+sentada+soleo+execucao'),
    ('Supino Reto com Halteres', 'Peito', 'livre', 'Desça com os cotovelos levemente abaixo da linha do banco, mantenha escápulas estáveis e suba sem perder o arco natural.', 'Banco reto, halteres', 'Halteres oferecem liberdade articular e boa amplitude, úteis para hipertrofia com controle fino de trajetória.', 'https://www.youtube.com/results?search_query=supino+reto+halter+execucao'),
    ('Supino Inclinado com Halteres', 'Peito', 'livre', 'Use inclinação moderada, peito alto e trajetória estável até próximo da linha superior do peitoral.', 'Banco inclinado, halteres', 'Inclinações moderadas tendem a distribuir melhor o estímulo para peitoral superior sem roubar demais para deltoide anterior.', 'https://www.youtube.com/results?search_query=supino+inclinado+halter+execucao'),
    ('Supino Inclinado com Barra', 'Peito', 'livre', 'Mantenha escápulas retraídas, desça ao alto do peito e controle o caminho da barra durante toda a série.', 'Banco inclinado, barra, anilhas', 'Boa opção pesada para peitoral clavicular, geralmente pedindo atenção extra à inclinação do banco e à fadiga de ombros.', 'https://www.youtube.com/results?search_query=supino+inclinado+barra+execucao'),
    ('Supino Reto com Barra', 'Peito', 'livre', 'Plante os pés, gere estabilidade no tronco e toque a barra com consistência sem perder o posicionamento das escápulas.', 'Banco reto, barra, anilhas', 'Compósito clássico para força e hipertrofia, com boa transferência para progressão de carga ao longo do bloco.', 'https://www.youtube.com/results?search_query=supino+reto+barra+execucao'),
    ('Crossover no Cabo', 'Peito', 'maquina', 'Aproxime as mãos em arco, mantenha peitoral ativo e evite transformar o exercício em movimento de ombro.', 'Polia alta ou média', 'Cabos mantêm tensão contínua e permitem enfatizar a fase final de adução horizontal.', 'https://www.youtube.com/results?search_query=crossover+no+cabo+execucao'),
    ('Crossover Polia Alta', 'Peito', 'maquina', 'Puxe em arco de cima para baixo, mantendo peito aberto e cotovelos levemente flexionados.', 'Polia alta', 'Variação útil para enfatizar fibras esternais e parte inferior do peitoral com tensão contínua.', 'https://www.youtube.com/results?search_query=crossover+polia+alta+execucao'),
    ('Crucifixo Máquina (Pec Deck)', 'Peito', 'maquina', 'Ajuste a máquina para alinhar ombros e cotovelos, feche os braços com controle e segure brevemente a contração.', 'Máquina pec deck', 'Alta estabilidade e boa proximidade da falha fazem desta opção uma boa ferramenta para volume de peitoral.', 'https://www.youtube.com/results?search_query=pec+deck+execucao'),
    ('Paralelas (Peito)', 'Peito', 'funcional', 'Incline levemente o tronco à frente, desça até amplitude segura e suba sem perder depressão das escápulas.', 'Barras paralelas', 'Quando bem executadas, podem gerar alto estímulo para peitoral inferior e tríceps, mas exigem boa tolerância de ombros.', 'https://www.youtube.com/results?search_query=paralelas+peito+execucao'),
    ('Desenvolvimento com Halteres', 'Ombro', 'livre', 'Empurre acima da cabeça sem colapsar a lombar, mantendo antebraços verticais e ritmo controlado.', 'Banco, halteres', 'Movimento base para deltoides com liberdade articular e bom potencial de progressão.', 'https://www.youtube.com/results?search_query=desenvolvimento+com+halteres+execucao'),
    ('Desenvolvimento Militar com Barra', 'Ombro', 'livre', 'Crie rigidez no tronco, leve a barra em linha eficiente e evite compensar inclinando o corpo para trás.', 'Barra, anilhas', 'Versão mais estável para progressão de carga, mas sensível à fadiga de tronco e mobilidade de ombros.', 'https://www.youtube.com/results?search_query=desenvolvimento+militar+barra+execucao'),
    ('Elevação Lateral', 'Ombro', 'livre', 'Suba os braços até perto da linha do ombro com cotovelos soltos e sem embalar o corpo.', 'Halteres', 'Altas repetições e controle fino costumam funcionar muito bem para deltoide lateral.', 'https://www.youtube.com/results?search_query=elevacao+lateral+halter+execucao'),
    ('Elevação Lateral no Cabo', 'Ombro', 'maquina', 'Mantenha tensão contínua desde a base, subindo de forma suave e controlada até a linha do ombro.', 'Polia baixa', 'O cabo melhora a tensão no início da curva e é excelente para aumentar estímulo sem usar muito impulso.', 'https://www.youtube.com/results?search_query=elevacao+lateral+cabo+execucao'),
    ('Crucifixo Inverso', 'Ombro', 'livre', 'Abra os braços sem estender demais a lombar e conduza o movimento pelos cotovelos.', 'Halteres ou banco inclinado', 'Aumenta o trabalho de deltoide posterior e ajuda a equilibrar padrões dominantes de empurrar.', 'https://www.youtube.com/results?search_query=crucifixo+inverso+execucao'),
    ('Crucifixo Inverso Máquina', 'Ombro', 'maquina', 'Ajuste o peito no apoio, abra com cotovelos guiando o movimento e evite trapézio alto dominar a fase final.', 'Máquina reverse pec deck', 'Excelente para deltoide posterior com alta estabilidade e fácil progressão por repetições.', 'https://www.youtube.com/results?search_query=crucifixo+inverso+maquina+execucao'),
    ('Face Pull', 'Ombro', 'maquina', 'Puxe a corda em direção ao rosto com cotovelos altos e rotação externa no final do gesto.', 'Polia alta, corda', 'Boa escolha para deltoide posterior, trapézio médio e saúde escapular dentro de blocos com muito supino.', 'https://www.youtube.com/results?search_query=face+pull+execucao'),
    ('Face Pull Corda (Polia Alta)', 'Ombro', 'maquina', 'Mantenha a corda alta, abra as mãos no final e finalize com escápulas controladas.', 'Polia alta, corda', 'Útil para estabilidade escapular e para complementar volume de ombro posterior e manguito.', 'https://www.youtube.com/results?search_query=face+pull+corda+execucao'),
    ('Puxada Pronada', 'Costas', 'maquina', 'Inicie deprimindo as escápulas e puxe levando os cotovelos para baixo, sem transformar em remada.', 'Polia alta', 'Boa variação vertical para dorsais e grande dorsal, especialmente quando a barra fixa ainda limita o volume total.', 'https://www.youtube.com/results?search_query=puxada+pronada+execucao'),
    ('Pulldown Pronado', 'Costas', 'maquina', 'Puxe em direção à parte alta do peito com tronco estável e amplitude controlada.', 'Polia alta', 'Ajuda a acumular volume em dorsais com menos instabilidade que a barra fixa.', 'https://www.youtube.com/results?search_query=pulldown+pronado+execucao'),
    ('Pulldown Supinado', 'Costas', 'maquina', 'Mantenha peito alto e cotovelos próximos ao corpo, puxando com foco em dorsais e flexores do cotovelo.', 'Polia alta', 'Pegada supinada pode melhorar sensação de dorsais para algumas pessoas e variar a distribuição do esforço.', 'https://www.youtube.com/results?search_query=pulldown+supinado+execucao'),
    ('Barra Fixa Pronada', 'Costas', 'funcional', 'Suba com o tronco estável, iniciando pela depressão escapular, e evite balanço nas pernas.', 'Barra fixa', 'Excelente para força relativa e dorsais, mas costuma exigir boa gestão de fadiga quando usada pesada.', 'https://www.youtube.com/results?search_query=barra+fixa+pronada+execucao'),
    ('Remada no Cabo', 'Costas', 'maquina', 'Puxe com o cotovelo, estabilize o tronco e finalize trazendo as escápulas para trás sem exagero de balanço.', 'Polia baixa', 'Boa ferramenta para densidade de costas, com fácil ajuste de carga e alto controle técnico.', 'https://www.youtube.com/results?search_query=remada+no+cabo+execucao'),
    ('Remada Baixa (Cabo Sentado)', 'Costas', 'maquina', 'Mantenha o tronco firme e conduza o puxador até a linha do abdômen sem usar impulso excessivo.', 'Cabo sentado', 'Variação estável para acumular volume de dorsais e romboides com boa repetibilidade.', 'https://www.youtube.com/results?search_query=remada+baixa+cabo+sentado+execucao'),
    ('Remada Unilateral com Halter', 'Costas', 'livre', 'Apoie o corpo com firmeza, puxe o halter próximo ao quadril e controle a descida.', 'Banco, halter', 'Muito útil para corrigir assimetrias e aumentar amplitude com foco unilateral.', 'https://www.youtube.com/results?search_query=remada+unilateral+halter+execucao'),
    ('Remada Curvada com Barra', 'Costas', 'livre', 'Incline o tronco com estabilidade, mantenha abdômen ativo e puxe a barra sem arredondar a coluna.', 'Barra, anilhas', 'Compósito importante para espessura de costas, porém mais custoso em fadiga lombar.', 'https://www.youtube.com/results?search_query=remada+curvada+barra+execucao'),
    ('T-Bar / Cavalinho', 'Costas', 'livre', 'Mantenha quadril fixo, peito aberto e traga a carga em direção à base do peito ou abdômen alto.', 'Barra T ou máquina cavalinho', 'Permite sobrecarga alta com apoio relativo melhor que a remada curvada tradicional.', 'https://www.youtube.com/results?search_query=remada+cavalinho+tbar+execucao'),
    ('Encolhimento com Halteres', 'Costas', 'livre', 'Eleve os ombros verticalmente, segure breve no topo e evite girar o pescoço durante a execução.', 'Halteres', 'Trabalho complementar para trapézio superior, geralmente melhor em cadência controlada do que com carga excessiva.', 'https://www.youtube.com/results?search_query=encolhimento+halter+execucao'),
    ('Rosca Alternada', 'Bíceps', 'livre', 'Suba supinando o antebraço, mantenha o cotovelo relativamente fixo e evite embalar o tronco.', 'Halteres', 'Boa para amplitude, coordenação bilateral e ajuste fino de trajetória.', 'https://www.youtube.com/results?search_query=rosca+alternada+execucao'),
    ('Rosca Direta com Barra', 'Bíceps', 'livre', 'Mantenha o braço próximo ao corpo, suba sem jogar o quadril e desça controlando até quase extensão total.', 'Barra reta ou EZ', 'Ótima para sobrecarga progressiva em bíceps, pedindo atenção a impulso e sobrecarga de punhos.', 'https://www.youtube.com/results?search_query=rosca+direta+barra+execucao'),
    ('Rosca Scott', 'Bíceps', 'maquina', 'Apoie bem o braço no banco Scott e controle a excêntrica sem relaxar no final da descida.', 'Banco Scott, barra ou máquina', 'Alta estabilidade e alongamento consistente fazem desta uma boa opção para volume localizado.', 'https://www.youtube.com/results?search_query=rosca+scott+execucao'),
    ('Rosca Martelo', 'Bíceps', 'livre', 'Use pegada neutra, cotovelos próximos ao corpo e subida limpa sem balanço.', 'Halteres', 'Variação útil para braquial e braquiorradial, ajudando no volume total de flexores do cotovelo.', 'https://www.youtube.com/results?search_query=rosca+martelo+execucao'),
    ('Rosca Inclinada com Halteres', 'Bíceps', 'livre', 'Mantenha os ombros para trás no banco inclinado e faça a subida sem deslocar o cotovelo para frente.', 'Banco inclinado, halteres', 'A posição alongada tende a gerar alta tensão em bíceps, excelente para complementar roscas mais pesadas.', 'https://www.youtube.com/results?search_query=rosca+inclinada+halter+execucao'),
    ('Tríceps Corda', 'Tríceps', 'maquina', 'Mantenha os cotovelos estáveis, empurre a corda para baixo e abra as mãos no final do movimento.', 'Polia alta, corda', 'Muito eficiente para volume de tríceps com baixa demanda técnica e boa tolerância a repetições moderadas e altas.', 'https://www.youtube.com/results?search_query=triceps+corda+execucao'),
    ('Tríceps Testa Barra EZ', 'Tríceps', 'livre', 'Desça a barra em direção à testa ou atrás dela com cotovelos estáveis e suba sem abrir demais os braços.', 'Barra EZ, banco', 'A posição alongada pode aumentar o estímulo na cabeça longa do tríceps, mas pede controle técnico para poupar cotovelos.', 'https://www.youtube.com/results?search_query=triceps+testa+barra+ez+execucao'),
    ('Tríceps Francês com Halter', 'Tríceps', 'livre', 'Alongue atrás da cabeça com controle e estenda o cotovelo sem deixar o braço abrir demais.', 'Halter', 'Boa opção para cabeça longa por trabalhar o tríceps em posição alongada do ombro.', 'https://www.youtube.com/results?search_query=triceps+frances+halter+execucao')
)
insert into public.exercicios (
  nome,
  grupo_muscular,
  tipo,
  execucao,
  equipamento,
  observacao_cientifica,
  video_url
)
select
  s.nome,
  s.grupo_muscular::muscle_group,
  s.tipo::exercise_type,
  s.execucao,
  s.equipamento,
  s.observacao_cientifica,
  s.video_url
from seed_exercicios s
where not exists (
  select 1
  from public.exercicios e
  where lower(trim(e.nome)) = lower(trim(s.nome))
);
